require 'json'

class LogMagic::SearchkickPrinter
  include ::LogMagic::JSONUtils

  def initialize(query_json, uuid)
    @query_json = query_json
    @uuid = uuid
  end

  def print
    """
    ElasticSearch query generated by Searchkick
    <------------------------------------------
    #{pretty_print_json(@query_json)}
    ------------------------------------------>
    http://localhost:7467/#{@uuid}
    """
  end
end
