require 'json'

class LogMagic::SearchkickPrinter
  def initialize(query_json, uuid)
    @query_json = query_json
    @uuid = uuid
  end

  def print
    """
    ElasticSearch query generated by Searchkick explained
    Copy and view in browser: http://localhost:7467/#{@uuid}
    <------------------------------------------>
    """
  end
end
